// GENERATED by tools/design/fetch_fluent.py from microsoft/fluentui-emoji@1ffb34c (MIT). Do not edit by hand.
package com.ledga.app.ui.design.icons

import com.ledga.app.R

/** Fluent Emoji 3D drawables by icon key (`fluent_<name>`, as stored in `categories.icon3d`). Use `Fluent.resOf`. */
object FluentIcons {
    val byKey: Map<String, Int> = mapOf(
        "fluent_antenna_bars" to R.drawable.fluent_antenna_bars,
        "fluent_artist_palette" to R.drawable.fluent_artist_palette,
        "fluent_bank" to R.drawable.fluent_bank,
        "fluent_bar_chart" to R.drawable.fluent_bar_chart,
        "fluent_bell" to R.drawable.fluent_bell,
        "fluent_bus" to R.drawable.fluent_bus,
        "fluent_busts_in_silhouette" to R.drawable.fluent_busts_in_silhouette,
        "fluent_check_mark_button" to R.drawable.fluent_check_mark_button,
        "fluent_cloud" to R.drawable.fluent_cloud,
        "fluent_coin" to R.drawable.fluent_coin,
        "fluent_credit_card" to R.drawable.fluent_credit_card,
        "fluent_dollar_banknote" to R.drawable.fluent_dollar_banknote,
        "fluent_droplet" to R.drawable.fluent_droplet,
        "fluent_floppy_disk" to R.drawable.fluent_floppy_disk,
        "fluent_fork_and_knife_with_plate" to R.drawable.fluent_fork_and_knife_with_plate,
        "fluent_fuel_pump" to R.drawable.fluent_fuel_pump,
        "fluent_globe_with_meridians" to R.drawable.fluent_globe_with_meridians,
        "fluent_graduation_cap" to R.drawable.fluent_graduation_cap,
        "fluent_high_voltage" to R.drawable.fluent_high_voltage,
        "fluent_hospital" to R.drawable.fluent_hospital,
        "fluent_house" to R.drawable.fluent_house,
        "fluent_inbox_tray" to R.drawable.fluent_inbox_tray,
        "fluent_incoming_envelope" to R.drawable.fluent_incoming_envelope,
        "fluent_label" to R.drawable.fluent_label,
        "fluent_locked" to R.drawable.fluent_locked,
        "fluent_magnifying_glass_tilted_left" to R.drawable.fluent_magnifying_glass_tilted_left,
        "fluent_memo" to R.drawable.fluent_memo,
        "fluent_mobile_phone" to R.drawable.fluent_mobile_phone,
        "fluent_mobile_phone_with_arrow" to R.drawable.fluent_mobile_phone_with_arrow,
        "fluent_money_bag" to R.drawable.fluent_money_bag,
        "fluent_money_with_wings" to R.drawable.fluent_money_with_wings,
        "fluent_outbox_tray" to R.drawable.fluent_outbox_tray,
        "fluent_p_button" to R.drawable.fluent_p_button,
        "fluent_package" to R.drawable.fluent_package,
        "fluent_party_popper" to R.drawable.fluent_party_popper,
        "fluent_repeat_button" to R.drawable.fluent_repeat_button,
        "fluent_rocket" to R.drawable.fluent_rocket,
        "fluent_shopping_bags" to R.drawable.fluent_shopping_bags,
        "fluent_shopping_cart" to R.drawable.fluent_shopping_cart,
        "fluent_sparkles" to R.drawable.fluent_sparkles,
        "fluent_television" to R.drawable.fluent_television,
        "fluent_warning" to R.drawable.fluent_warning,
        "fluent_wrapped_gift" to R.drawable.fluent_wrapped_gift,
        "fluent_wrench" to R.drawable.fluent_wrench,
    )
}
