#!/usr/bin/env python3
"""Vendor Microsoft Fluent Emoji 3D (MIT) as 96 px lossless WebP for Ledga (spec 10.3, refinement R23).

Downloads the pinned PNGs, scales them to 96 px, writes app/src/main/res/drawable-nodpi/fluent_<key>.webp,
the generated lookup FluentIcons.kt and the licence. Re-running gives identical output.
Requires: pip install pillow
"""
import io
import json
import pathlib
import re
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from concurrent.futures import ThreadPoolExecutor

from PIL import Image

SHA = "1ffb34c752ecf5d402f04cfb4b392c77f57c54bc"
RAW = f"https://raw.githubusercontent.com/microsoft/fluentui-emoji/{SHA}"
SIZE = 96
MAX_BYTES = 16_000

# key -> asset folder. Category keys match Categories.SEED icon3d ("fluent_" + key).
CATEGORY = {
    "high_voltage": "High voltage", "droplet": "Droplet", "antenna_bars": "Antenna bars",
    "television": "Television", "house": "House",
    "fuel_pump": "Fuel pump", "wrench": "Wrench", "p_button": "P button",
    "shopping_cart": "Shopping cart", "fork_and_knife_with_plate": "Fork and knife with plate", "bus": "Bus",
    "mobile_phone": "Mobile phone", "shopping_bags": "Shopping bags", "hospital": "Hospital",
    "graduation_cap": "Graduation cap",
    "outbox_tray": "Outbox tray", "dollar_banknote": "Dollar banknote", "money_with_wings": "Money with wings",
    "globe_with_meridians": "Globe with meridians", "package": "Package",
    "inbox_tray": "Inbox tray", "coin": "Coin", "wrapped_gift": "Wrapped gift",
    "money_bag": "Money bag", "bank": "Bank", "credit_card": "Credit card", "repeat_button": "Repeat button",
}
# Onboarding, You rows and empty states.
CHROME = {
    "artist_palette": "Artist palette", "bar_chart": "Bar chart", "bell": "Bell",
    "busts_in_silhouette": "Busts in silhouette", "check_mark_button": "Check mark button", "cloud": "Cloud",
    "floppy_disk": "Floppy disk", "incoming_envelope": "Incoming envelope", "label": "Label", "locked": "Locked",
    "magnifying_glass_tilted_left": "Magnifying glass tilted left", "memo": "Memo",
    "mobile_phone_with_arrow": "Mobile phone with arrow", "party_popper": "Party popper", "rocket": "Rocket",
    "sparkles": "Sparkles", "warning": "Warning",
}
# What a category of the person's own can take (R68): everyday things no built-in category uses.
USER_CHOICE = {
    "pill": "Pill", "dog_face": "Dog face", "baby_bottle": "Baby bottle", "airplane": "Airplane",
    "books": "Books", "hot_beverage": "Hot beverage", "scissors": "Scissors", "seedling": "Seedling",
    "church": "Church", "hammer_and_wrench": "Hammer and wrench", "soccer_ball": "Soccer ball", "ticket": "Ticket",
    "motorcycle": "Motorcycle", "broom": "Broom", "lipstick": "Lipstick", "laptop": "Laptop",
}

ROOT = pathlib.Path(__file__).resolve().parents[2]
RES = ROOT / "app/src/main/res/drawable-nodpi"
KOTLIN = ROOT / "app/src/main/java/com/ledga/app/ui/design/icons/FluentIcons.kt"
LICENSE = ROOT / "app/src/main/assets/licenses/fluentui-emoji-MIT.txt"
CATALOG = ROOT / "app/src/main/assets/icons3d"
CATALOG_QUALITY = 90  # R86: lossy q90, alpha exact; the 60 drawables stay lossless
GROUPS = ["Smileys & Emotion", "People & Body", "Animals & Nature", "Food & Drink", "Travel & Places",
          "Activities", "Objects", "Symbols", "Flags"]
PNG = re.compile(r"assets/([^/]+)/(?:Default/)?3D/(.+?)_3d(?:_default)?\.png")


def fetch(url: str) -> bytes:
    """GitHub's raw host drops the odd request (503) across ~3,000 downloads: a few tries, then give up loudly."""
    for attempt in range(5):
        try:
            with urllib.request.urlopen(url, timeout=60) as response:
                return response.read()
        except (urllib.error.HTTPError, urllib.error.URLError, TimeoutError) as e:
            if attempt == 4 or (isinstance(e, urllib.error.HTTPError) and e.code < 500):
                raise
            time.sleep(2 ** attempt)
    raise AssertionError("unreachable")


def main() -> None:
    icons = {**CATEGORY, **CHROME, **USER_CHOICE}
    if len(icons) != len(CATEGORY) + len(CHROME) + len(USER_CHOICE):
        sys.exit("a key is listed twice")
    RES.mkdir(parents=True, exist_ok=True)
    for old in RES.glob("fluent_*.webp"):
        old.unlink()
    total = 0
    for key, folder in sorted(icons.items()):
        url = f"{RAW}/assets/{urllib.parse.quote(folder)}/3D/{key}_3d.png"
        source = Image.open(io.BytesIO(fetch(url))).convert("RGBA")
        if source.size != (256, 256):
            sys.exit(f"{key}: unexpected source size {source.size}")
        out = io.BytesIO()
        source.resize((SIZE, SIZE), Image.LANCZOS).save(out, "WEBP", lossless=True, quality=100, method=6)
        data = out.getvalue()
        if len(data) > MAX_BYTES:
            sys.exit(f"{key}: {len(data)} bytes > {MAX_BYTES}")
        (RES / f"fluent_{key}.webp").write_bytes(data)
        total += len(data)
    lines = [
        f"// GENERATED by tools/design/fetch_fluent.py from microsoft/fluentui-emoji@{SHA[:7]} (MIT). Do not edit by hand.",
        "package com.ledga.app.ui.design.icons",
        "",
        "import com.ledga.app.R",
        "",
        "/** Fluent Emoji 3D drawables by icon key (`fluent_<name>`, as stored in `categories.icon3d`). Use `Fluent.resOf`. */",
        "object FluentIcons {",
        "    val byKey: Map<String, Int> = mapOf(",
    ]
    lines += [f'        "fluent_{key}" to R.drawable.fluent_{key},' for key in sorted(icons)]
    lines += ["    )", "}", ""]
    KOTLIN.write_text("\n".join(lines))
    LICENSE.parent.mkdir(parents=True, exist_ok=True)
    LICENSE.write_bytes(fetch(f"{RAW}/LICENSE"))
    print(f"{len(icons)} icons, {total} bytes")


def key_of(name: str) -> str:
    """The file name's words as an icon key: "face_with_head-bandage" → "face_with_head_bandage"."""
    return re.sub(r"_+", "_", re.sub(r"[^a-z0-9]+", "_", name.lower())).strip("_")


def catalog() -> None:
    """Every 3D icon at SHA: assets/icons3d/<key>.webp (skipping keys bundled as drawables) and index.tsv."""
    tree = json.loads(fetch(f"https://api.github.com/repos/microsoft/fluentui-emoji/git/trees/{SHA}?recursive=1"))
    if tree.get("truncated"):
        sys.exit("the tree listing is truncated")
    found = {}
    for entry in tree["tree"]:
        m = PNG.fullmatch(entry["path"])
        if m:
            found[m.group(1)] = (key_of(m.group(2)), entry["path"])
    keys = [k for k, _ in found.values()]
    if len(keys) != len(set(keys)):
        sys.exit("two icons share a key")
    bundled = set(CATEGORY) | set(CHROME) | set(USER_CHOICE)
    CATALOG.mkdir(parents=True, exist_ok=True)
    for old in CATALOG.glob("*.webp"):
        old.unlink()

    def one(folder: str):
        key, path = found[folder]
        meta = json.loads(fetch(f"{RAW}/assets/{urllib.parse.quote(folder)}/metadata.json"))
        if meta["group"] not in GROUPS:
            sys.exit(f"{folder}: unknown group {meta['group']}")
        size = 0
        if key not in bundled:
            source = Image.open(io.BytesIO(fetch(f"{RAW}/{urllib.parse.quote(path)}"))).convert("RGBA")
            out = io.BytesIO()
            source.resize((SIZE, SIZE), Image.LANCZOS).save(out, "WEBP", quality=CATALOG_QUALITY, alpha_quality=100, method=6)
            (CATALOG / f"{key}.webp").write_bytes(out.getvalue())
            size = len(out.getvalue())
        words = "|".join(w.replace("|", " ").replace("\t", " ") for w in meta.get("keywords", []))
        return key, meta.get("cldr") or folder, meta["group"], words, size

    with ThreadPoolExecutor(max_workers=8) as pool:
        rows = list(pool.map(one, sorted(found)))
    rows.sort(key=lambda r: (GROUPS.index(r[2]), r[1], r[0]))
    lines = ["key\tname\tgroup\tkeywords"] + [f"fluent_{k}\t{n}\t{g}\t{w}" for k, n, g, w, _ in rows]
    (CATALOG / "index.tsv").write_text("\n".join(lines) + "\n")
    print(f"{len(rows)} icons, {sum(r[4] for r in rows)} bytes of assets")


if __name__ == "__main__":
    catalog() if sys.argv[1:] == ["--catalog"] else main()
