#!/usr/bin/env python3
"""Vendor Microsoft Fluent Emoji 3D (MIT) as 96 px lossless WebP for Ledga (spec 10.3, refinement R23).

Downloads the pinned PNGs, scales them to 96 px, writes app/src/main/res/drawable-nodpi/fluent_<key>.webp,
the generated lookup FluentIcons.kt and the licence. Re-running gives identical output.
Requires: pip install pillow
"""
import io
import pathlib
import sys
import urllib.parse
import urllib.request

from PIL import Image

SHA = "1ffb34c752ecf5d402f04cfb4b392c77f57c54bc"
RAW = f"https://raw.githubusercontent.com/microsoft/fluentui-emoji/{SHA}"
SIZE = 96
MAX_BYTES = 16_000

# key -> asset folder. Category keys match Categories.SEED icon3d ("fluent_" + key).
CATEGORY = {
    "high_voltage": "High voltage", "droplet": "Droplet", "antenna_bars": "Antenna bars",
    "television": "Television", "house": "House",
    "fuel_pump": "Fuel pump", "wrench": "Wrench", "p_button": "P button",
    "shopping_cart": "Shopping cart", "fork_and_knife_with_plate": "Fork and knife with plate", "bus": "Bus",
    "mobile_phone": "Mobile phone", "shopping_bags": "Shopping bags", "hospital": "Hospital",
    "graduation_cap": "Graduation cap",
    "outbox_tray": "Outbox tray", "dollar_banknote": "Dollar banknote", "money_with_wings": "Money with wings",
    "globe_with_meridians": "Globe with meridians", "package": "Package",
    "inbox_tray": "Inbox tray", "coin": "Coin", "wrapped_gift": "Wrapped gift",
    "money_bag": "Money bag", "bank": "Bank", "credit_card": "Credit card", "repeat_button": "Repeat button",
}
# Onboarding, You rows and empty states.
CHROME = {
    "artist_palette": "Artist palette", "bar_chart": "Bar chart", "bell": "Bell",
    "busts_in_silhouette": "Busts in silhouette", "check_mark_button": "Check mark button", "cloud": "Cloud",
    "floppy_disk": "Floppy disk", "incoming_envelope": "Incoming envelope", "label": "Label", "locked": "Locked",
    "magnifying_glass_tilted_left": "Magnifying glass tilted left", "memo": "Memo",
    "mobile_phone_with_arrow": "Mobile phone with arrow", "party_popper": "Party popper", "rocket": "Rocket",
    "sparkles": "Sparkles", "warning": "Warning",
}
# What a category of the person's own can take (R68): everyday things no built-in category uses.
USER_CHOICE = {
    "pill": "Pill", "dog_face": "Dog face", "baby_bottle": "Baby bottle", "airplane": "Airplane",
    "books": "Books", "hot_beverage": "Hot beverage", "scissors": "Scissors", "seedling": "Seedling",
    "church": "Church", "hammer_and_wrench": "Hammer and wrench", "soccer_ball": "Soccer ball", "ticket": "Ticket",
    "motorcycle": "Motorcycle", "broom": "Broom", "lipstick": "Lipstick", "laptop": "Laptop",
}

ROOT = pathlib.Path(__file__).resolve().parents[2]
RES = ROOT / "app/src/main/res/drawable-nodpi"
KOTLIN = ROOT / "app/src/main/java/com/ledga/app/ui/design/icons/FluentIcons.kt"
LICENSE = ROOT / "app/src/main/assets/licenses/fluentui-emoji-MIT.txt"


def fetch(url: str) -> bytes:
    with urllib.request.urlopen(url) as response:
        return response.read()


def main() -> None:
    icons = {**CATEGORY, **CHROME, **USER_CHOICE}
    if len(icons) != len(CATEGORY) + len(CHROME) + len(USER_CHOICE):
        sys.exit("a key is listed twice")
    RES.mkdir(parents=True, exist_ok=True)
    for old in RES.glob("fluent_*.webp"):
        old.unlink()
    total = 0
    for key, folder in sorted(icons.items()):
        url = f"{RAW}/assets/{urllib.parse.quote(folder)}/3D/{key}_3d.png"
        source = Image.open(io.BytesIO(fetch(url))).convert("RGBA")
        if source.size != (256, 256):
            sys.exit(f"{key}: unexpected source size {source.size}")
        out = io.BytesIO()
        source.resize((SIZE, SIZE), Image.LANCZOS).save(out, "WEBP", lossless=True, quality=100, method=6)
        data = out.getvalue()
        if len(data) > MAX_BYTES:
            sys.exit(f"{key}: {len(data)} bytes > {MAX_BYTES}")
        (RES / f"fluent_{key}.webp").write_bytes(data)
        total += len(data)
    lines = [
        f"// GENERATED by tools/design/fetch_fluent.py from microsoft/fluentui-emoji@{SHA[:7]} (MIT). Do not edit by hand.",
        "package com.ledga.app.ui.design.icons",
        "",
        "import com.ledga.app.R",
        "",
        "/** Fluent Emoji 3D drawables by icon key (`fluent_<name>`, as stored in `categories.icon3d`). Use `Fluent.resOf`. */",
        "object FluentIcons {",
        "    val byKey: Map<String, Int> = mapOf(",
    ]
    lines += [f'        "fluent_{key}" to R.drawable.fluent_{key},' for key in sorted(icons)]
    lines += ["    )", "}", ""]
    KOTLIN.write_text("\n".join(lines))
    LICENSE.parent.mkdir(parents=True, exist_ok=True)
    LICENSE.write_bytes(fetch(f"{RAW}/LICENSE"))
    print(f"{len(icons)} icons, {total} bytes")


if __name__ == "__main__":
    main()
