#!/usr/bin/env python3
"""Vendor Phosphor icons (MIT) as Compose ImageVectors for Ledga (spec 10.3, refinement R24).

Downloads the pinned SVGs, checks each is plain <path> data on Phosphor's 256 viewBox, and writes
app/src/main/java/com/ledga/app/ui/design/icons/Ph.kt plus the licence. Re-running gives identical output.
"""
import pathlib
import re
import sys
import urllib.request

VERSION = "2.1.1"
BASE = f"https://unpkg.com/@phosphor-icons/core@{VERSION}"
REGULAR = [
    "arrow-clockwise", "arrow-counter-clockwise", "arrow-down-left", "arrow-left", "arrow-right", "arrow-up-right",
    "bell", "bell-slash", "calendar-blank", "caret-down", "caret-left", "caret-right", "caret-up", "chart-bar",
    "check", "check-circle", "copy", "dots-three", "download-simple", "eye-slash", "hand-coins", "house", "info",
    "magnifying-glass", "pencil-simple", "plus", "receipt", "share-network", "sim-card", "sliders-horizontal",
    "trash", "user-circle", "warning", "warning-circle", "x",
]
FILL = ["chart-bar", "house", "receipt", "user-circle"]
BOLD = ["arrow-down-left", "arrow-up-right", "caret-down", "caret-right", "caret-up", "check", "plus", "x"]

ROOT = pathlib.Path(__file__).resolve().parents[2]
OUT = ROOT / "app/src/main/java/com/ledga/app/ui/design/icons/Ph.kt"
LICENSE = ROOT / "app/src/main/assets/licenses/phosphor-MIT.txt"

SVG = re.compile(r'^<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" fill="currentColor">(.*)</svg>$', re.S)
PATH = re.compile(r'<path d="([^"]+)"/>')
SUFFIX = {"regular": "", "fill": "Fill", "bold": "Bold"}


def fetch(url: str) -> str:
    with urllib.request.urlopen(url) as response:
        return response.read().decode("utf-8")


def kotlin_name(name: str, weight: str) -> str:
    return "".join(part.capitalize() for part in name.split("-")) + SUFFIX[weight]


def path_data(name: str, weight: str) -> list:
    file = name if weight == "regular" else f"{name}-{weight}"
    svg = fetch(f"{BASE}/assets/{weight}/{file}.svg").strip()
    match = SVG.match(svg)
    if not match:
        sys.exit(f"{weight}/{file}: unexpected <svg> header")
    body = match.group(1)
    paths = PATH.findall(body)
    if not paths or PATH.sub("", body).strip():
        sys.exit(f"{weight}/{file}: only <path d=...> elements are supported")
    return paths


def main() -> None:
    icons = []
    for weight, names in (("regular", REGULAR), ("fill", FILL), ("bold", BOLD)):
        for name in names:
            icons.append((kotlin_name(name, weight), path_data(name, weight)))
    icons.sort()
    lines = [
        f"// GENERATED by tools/design/fetch_phosphor.py from @phosphor-icons/core {VERSION} (MIT). Do not edit by hand.",
        "package com.ledga.app.ui.design.icons",
        "",
        "import androidx.compose.ui.graphics.vector.ImageVector",
        "",
        "/** Phosphor chrome icons (spec §10.3): regular for UI, `…Fill` for the active tab, `…Bold` for small inline glyphs. */",
        "object Ph {",
    ]
    for kotlin, paths in icons:
        args = ", ".join(f'"{d}"' for d in paths)
        lines.append(f'    val {kotlin}: ImageVector by lazy {{ phosphor("{kotlin}", {args}) }}')
    lines += ["", "    /** Every vendored icon by name (tests, the licences screen). */", "    val all: Map<String, ImageVector>", "        get() = mapOf("]
    lines += [f'            "{kotlin}" to {kotlin},' for kotlin, _ in icons]
    lines += ["        )", "}", ""]
    OUT.write_text("\n".join(lines))
    LICENSE.parent.mkdir(parents=True, exist_ok=True)
    LICENSE.write_text(fetch(f"{BASE}/LICENSE"))
    print(f"{len(icons)} icons -> {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
